CONTRIBUTING.md
=> Remove redundancy in CONTRIBUTING.md

docs/knowledge-contribution-guide.md
**Description:** Only accepting files from wiki
=> Fix error in knowledge guide

knowledge/README.md
=> Fix invalid links in knowledge README

.github/labeler.yml, .github/workflows/label.yml, .github/workflows/lint.yml
Fixes https://github.com/instruct-lab/taxonomy/issues/682
Replacement PR for #683.
=> Update notice comments to single line SPDX-License-Identifier

.github/pull_request_template.md, docs/contributing_via_GH_UI.md, docs/triaging/safe-responses.md
Updating a few broken links and removing some dashes
=> docs: Avoid-these-topics has moved

.github/workflows/docs.yml, .github/workflows/lint.yml
We include the workflow file in the trigger to test when a PR modifies the workflow.
=> Run workflows when they are changed in a PR to test them

.github/workflows/coc_violation_analysis.yml
Adding workflow to trigger CoC analysis, post `Lint` workflow is successful.
CoC analysis validates the contribution yml files against the following areas:
- Privacy (Personal Identifiable Information)
- HAP (Hate, Abuse, Profanity)
- Inappropriate Content (Adult, Illegal, Gambling)
- Regulated Industries (Medical, Financial)
=> Add workflow to trigger CoC violation analysis

.github/workflows/coc_violation_analysis.yml
Set some defaults and use github.events context instead of bash commands.
=> Workflow improvements for new insight workflow

.github/workflows/coc_violation_analysis.yml
This will allow us to see which PR a specific workflow run was for.
=> Add pull request number to workflow run-name

.github/workflows/coc_violation_analysis.yml
We also only run the workflow if there is a PR associated.
=> Fix workflows use of github context

.github/workflows/lint.yml
See https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#example-using-bash
=> workflow: Access secret through env var

.github/workflows/label.yml
Lets let the bot do the work for us.
=> Added a automatic note for triage-uncertain

README.md
Renaming thermo Dir related to #955 
/cc @jjasghar 
Related to triage call.
=> Abstract out radioisotope_thermo_generator dir rename (#1116)

docs/knowledge-contribution-guide.md
**Description:** Adds more descriptions on markdowns for knowledge contributions
=> Docs: Add specific conversion description to knowledge contribution guide

compositional_skills/extraction/inference/quantitative/asciidoc/tables/qna.yaml, compositional_skills/writing/freeform/emoji/qna.yaml, compositional_skills/writing/freeform/riddles/attribution.txt, compositional_skills/writing/freeform/riddles/qna.yaml
These were created before the
- version: 2 was required
- attribution.txt was also required
=> Fixes for the linter

.github/workflows/label.yml, docs/knowledge-contribution-guide.md
Some tidying up in the label workflow.
=> Cleanup label workflow

README.md
Description: Updating knowledge example in README per new SDG schema
=> [DOCS] Updating knowledge examples in taxonomy README.md

.github/workflows/lint.yml, scripts/check-yaml.py, scripts/requirements.txt
We replace parsing/validation code to use the shared code from instructlab-schema package.
=> Use instructlab-schema package to parse qna.yaml files

README.md
We don't need to use the google form anymore.
=> Removed knowledge submission link

README.md
- Removed wikilink code
- Added an array for the document section
/cc @juliadenham
=> Removed wikilink from the knowledge example

.github/workflows/stale_bot.yml
Don't stale out things that are good for the community to help with.
=> Don't stale out good-first-issue

README.md, docs/README.md, docs/taxonomy_diagram.md
Updated the diagram because of #1215.
/cc @mcorbin-ibm @juliadenham
=> taxonomy mermaid diagram

README.md
Fix Knowledge yaml examples indentation
=> Update README.md, Knowledge yaml examples section (#1)

docs/template_qna.yaml
Sometimes it's nice to have everything templated out to start with.
=> Added taxonomy template

compositional_skills/writing/grounded/editing/content/attribution.txt, compositional_skills/writing/grounded/editing/content/qna.yaml
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.
**Describe the contribution to the taxonomy**
<Added compositional skill: Rewrite complex texts in an easier way>
- Understands a complex text and rewrites it in an easier way
- Context is the given complex text
- Useful for normal people to understand complicated topics 
**Input given at the prompt**
```
...
```
**Response from the original model**
```
...
```
**Response from the fine-tuned model**
```
...
```
**Contribution checklist**
- [] The contribution was tested with `ilab generate`
- [] No errors or warnings were produced by `ilab generate`
=> New skill: Rewrite complex texts

knowledge/science/animals/birds/black_capped_chickadee/attribution.txt, knowledge/science/animals/birds/black_capped_chickadee/qna.yaml
This is the combined Black CappedPRs sfrom Red Hat Summit 2024.
This superseeds #873
=> Black Capped (combined)

docs/triaging/safe-responses.md
This PR does two things:
- Update responses to make more sense to users, as some folks may not know what diversity means in context.
- Add link fixes and spelling error fixes
=> Patch safe responses
