instructlab/taxonomy

- .github/scripts/check-yaml.py
After validating the qna.yaml, we also confirm the presence of a non-empty attribution.txt file in the same folder.
> validation: Confirm the qna.yaml file has a non-empty attribution.txt

- docs/triaging/triaging-contributions.md
**Description:** Adding actuate labels to triaging documentation
> Fixing triaging docs

- .github/pull_request_template.md
Add a checkbox to make sure taxonomy contributions follow (don't fall into) the avoid-topics list
FYI @jjasghar @lhawthorn
---
**Contribution checklist**
> chore: Add avoid topics to PR template

- .github/workflows/label.yml
The syncing was re-adding existing labels on each push to a PR which caused issues for the bot.
> ci: Change labeler configuration to remove syncing

- .github/pull_request_template.md
- README.md
- docs/KNOWLEDGE_GUIDE.md
- docs/SKILLS_GUIDE.md
- docs/triaging/safe-responses.md
**Description:** Thought that the skills_guide and knowlegde_guide should belong in the taxonomy repo instead of the community repo. Just copied the files and fixed the links. Still working on fixing Avoid these topics section, might have to do in anoter PR 
**Additional info:** 
Removing/fixing content in community repo in https://github.com/instructlab/community/pull/228
>  DOCS: Moving skills and knowledge guide to taxonomy repo

- .github/dependabot.yml
- .github/workflows/actionlint.yml
- .github/workflows/label.yml
- .github/workflows/lint.yml
- .github/workflows/matchers/actionlint.json
- .github/workflows/stale_bot.yml
We use SHAs instead of tag names to refer to action versions.
Dependabot will help use manage the SHAs.
Update permissions to minimum necessary.
Add harden-runner to monitor egress of action. After some time, we can
tighten the egress to limit hosts/ports.
We also add a matcher for actionlint errors.
> Harden action workflows

- README.md
Fixed broken link to the taxonomy tree in the readme.md
> Link to Taxonomy Tree in readme.md is broken

- .github/workflows/stale_bot.yml
We got overwhelmed with requests from Summit, this is to give the bot the way to stale out PRs that haven't been touched in 2 weeks.
> Updated per the triager conversation

- .github/workflows/stale_bot.yml
Since the stale bot is configured, we also need to configure for issues. When an issue is marked stale, we want a comment added to alert those following the issue. We also want to configure the days rather than use the default.
Finally, we exempt PRs labeled triage-approved from being marked stale to allow the necessary time for such PRs to go through the backend process.
> stale: Update configuration for issue staleness

- .github/workflows/coc_violation_analysis.yml
The workflow was not running after some lint operations on a pull request such as after a force push on an existing PR. So we remove the PR number check to see if the workflow runs when expected.
> Remove pull number check from workflow run

- .github/scripts/check-yaml.py
We no longer skip schema validation if linting reports an error.
> check_yaml: Always run schema validation

- .github/scripts/check-yaml.py
The top-level element of a yaml document can be an object (key-value pairs) or a list. We now test and provide an error message if the top-level element is not an object.
See https://github.com/instructlab/instructlab/issues/1170
> validation: Confirm yaml file contents are an object

- .github/workflows/lint.yml
This way of printing the output does not work properly and appears to have caused a failure in the step.
A better solution, if needed:
jq '.' "$GITHUB_EVENT_PATH"
> Remove faulty debug output

- .github/workflows/insight.yml
- .github/workflows/lint.yml
We pass the pull request number as an artifact from the lower privilege pull_request workflow to the higher privilege workflow_run workflow. The higher privilege workflow_run workflow has access to the secret for the curl post operation.
See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
> workflow: Configure insight analysis to a workflow_run

- .github/workflows/insight.yml
- .github/workflows/lint.yml
Some pull requests are not about skill or knowledge contributions. We change to always upload an artifact so the insight workflow wont fail because it cannot download the artifact. In the case were the PR does not contain qna.yaml, we pass the pull request number 0 so the insight workflow can avoid invoking the insight analysis.
> workflow: Handle when a pull request does not contain qna.yaml

- .github/workflows/insight.yml
If there is a display_title from the triggering pull request, we use it. Otherwise we use the insight workflow name. This will help in mapping insight workflow runs to the triggering pull request.
> workflow: Set insight workflow run-name to the display_title

- .github/scripts/check-yaml.py
- README.md
- knowledge/README.md
We introduce a relaxed schema as v1 which will accept all existing taxonomy files in the main branch of the taxonomy repo. The current v1 schema is renamed to v2 and will be used for future contributions to the taxonomy repo.
The check_yaml script is updated to allow a schema version to be specified. When the schema-version option is not specified, the script will use the latest schema version from the schema base. If the schema-version is specified as a non-positive integer, then the script will use the version key from the YAML document for the schema version to use.
The script is also changed to only check for attribution.txt when the schema version is higher than 1.
See https://github.com/instructlab/instructlab/issues/989
Depends on https://github.com/instructlab/schema/pull/11
> schema: Define a relaxed schema as v1 and move current schema to v2

- docs/contributing_via_GH_UI.md
It is `YAML example` for knowledge as changed in the PR (vs `skills example`).
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.
**Contribution checklist**
- [ x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ x] Content does not include PII or otherwise sensitive or confidential information
- [ x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines
> Fix example type

- .github/workflows/update-CoC-report.yml
Added a new workflow to automate the process of updating a Pull Request (PR) record when a PR is closed. The workflow sends an HTTP request to the Code of Conduct (CoC) Handler, ensuring that the PR status is accurately reflected in our records.
> workflow: Add workflow to update CoC report on PR close event

- .github/workflows/stale_bot.yml
The label for ready PRs was changed to e2e-ready. So we need to update the stale bot config to match the new label name.
> Update stale_bot.yml to exempt e2e-ready label

- README.md
the example yaml in contributing knowledge has invalid indenting
```
31:4: [warning] wrong indentation: expected 2 but found 3 (indentation
```
> fix yaml indenting of example qna

- docs/knowledge-contribution-guide.md
This adds the official PR table to the knowledge-contribution-guide and closes #786.
> Added table from #786

- .github/workflows/lint.yml
We re-add knowledge since the v1 knowledge is removed. We also use the default yamllint config from the instructlab-schema package. This now no longer lints for line length.
> lint action: Update configuration for new taxonomy layout

- compositional_skills/grounded/linguistics/inclusion/attribution.txt
- compositional_skills/grounded/linguistics/inclusion/qna.yaml
**Made in collaboration with [shucshar](https://github.com/shucshar)**
Methodology: [Generative Design](https://www.researchgate.net/publication/242386653_Generative_Tools_for_Co-designing)
**Describe the contribution to the taxonomy**
What: A skill to flag non inclusive IT terminology usage and suggest inclusive IT terminology replacements.
Why: According to [McLean and Company’s HR Trends Report 2023](https://hr.mcleanco.com/research/ss/hr-trends-report-2023?initiate_downloads=false), DEI professionals report that the top challenge was lacking dedicated time to do dedicated DEI work (n=224 organizations reporting in, 59% indicated dedicated time was biggest challenge.)
84% of the reporting sample organizations indicate fostering a culture of belonging is one of the primary areas of …
> Inclusive IT terminology

- compositional_skills/general/synonyms/attribution.txt
- compositional_skills/general/synonyms/qna.yaml
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.
**Describe the contribution to the taxonomy**
- ... List specific number synonyms for one word
- ... List one synonyms for one word
- ...List two synonyms for one word
- ... List three synonyms for one word
**Input given at the prompt**
```
(instructlab_vv) [root@dell-r640-041 synonyms]#  ilab generate --num-instructions 10
llama_cpp_python is built without hardware acceleration. ilab generate will be very slow.
Generating synthetic data using 'merlinite-7b-lab-Q4_K_M' model, taxonomy:'/home/instructlab/taxonomy' against http://127.0.0.1:8000/v1 server
INFO 2024-05-26 …
```
> Skill:List specific number synonyms for one word

- knowledge/science/astronomy/constellations/phoenix/qna.yaml
Noticed the following error when  running `instructlab.sdg.generate_data()` with the `cmb-run-2024-08-26` branch: `ERROR]: data/taxonomy/knowledge/science/astronomy/constellations/phoenix/qna.yaml:199:1 too many blank lines (1 > 0) (empty-lines)`
This PR removes the extra line from the end of the `data/taxonomy/knowledge/science/astronomy/constellations/phoenix/qna.yaml` to adderess the error.
> Fix 'too many blank lines' error in phoenix/qna.yaml by removing extra blank lines

- compositional_skills/linguistics/synonyms/qna.yaml
Looks like a typo, the one question didn't match the answer.
**Describe the contribution to the taxonomy**
- Fix for mismatch between question and answer.
**Input given at the prompt**
**Contribution checklist**
When asking the model about synonyms, I didn't notice any wrong answer. Maybe this specific q'n'a was eliminated during training?
> Fix typo in compositional_skills/linguistics/synonyms/qna.yaml
